### ISSUE TITLE
gem completion for build and install

### ISSUE THREAD

**Issue by kronn** [mernen/completion-ruby#10]
When completing the build-command, it would be helpful to complete all the *.gemspec files after the command. Likewise, when installing, it would be helpful to complete *.gem files from the local directory.

The standard "return all files and directories in the current directory" works a bit, but is IMHO not as helpful as it could be.

**Comment by mernen** [comment]
Well, it took *a bit* longer than reasonable, but here it is!

**Comment by kronn** [comment]
Nice. Thanks for the work.

And no worries for the time it took. You have a life as well. This improves my life now, and I am happy about it. :smile:
