### ISSUE TITLE
rails generate/g subcommands not completing

### ISSUE THREAD

**Issue by suan** [mernen/completion-ruby#13]
`rails generate` itself autocompletes, but past that, it just falls back to file completion... weird cause eg `rails plugin ` actually autocompletes to `install remove` (even though its really slow) so _some_ subcommands are working...

**Comment by mernen** [comment]
I'm quite busy this weekend, but I'll see if I can have a look at that over the next one.

**Comment by suan** [comment]
Really appreciate it! Let me know if you need any other debugging info

Also, my rails executable maps to ./bin/rails and is springified

**Comment by mernen** [comment]
Sorry for ignoring this for so long. Should be fixed now!
