### ISSUE TITLE
tag the release?

### ISSUE THREAD

**Issue by chenrui333** [mernen/completion-ruby#15]
👋 I wonder if you can help tag the release so that the downstream package manager (like homebrew) can pick up the new changes. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/80895

cc @mernen

**Comment by mernen** [comment]
Hi, I'm not familiar with Homebrew's livecheck. I just have to create a tag?

**Comment by chenrui333** [comment]
yeah, just a tag is good enough, thanks!

**Comment by mernen** [comment]
Alright, I suppose this is as good time as any to declare a stable v1.0.0 release. Tag created!

**Comment by chenrui333** [comment]
that is great, thanks! Let me update the associated PR :)

**Comment by chenrui333** [comment]
Thank for the help!
