### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by dklotz** [mernen/completion-ruby#4]
At the moment, completion-rails doesn't seem to recognize rails 4 projects as such, when I try to complete `rails <TAB>` in a newly generated rails 4 project, all the commands it offers me are `new` & `plugin`.

Apart from recognizing that I'm actually in a rails project folder, I don't know if anything else needs to be adapted (haven't done much with rails 4, yet).

**Comment by mernen** [comment]
Since there has been no further information and no new complaints, I’m closing this one. Please reopen with more details if issues persist.
