### ISSUE TITLE
bundler completion not working

### ISSUE THREAD

**Issue by jrochkind** [mernen/completion-ruby#7]
bundler completion does not seem to be working at all for me. Just has no effect. Not being great at reading bash, I'm not sure how to troubleshoot, any advice?

**Comment by mernen** [comment]
Let’s start with the basics…

1. Which bash version are you using? (If you’re on MacOS and haven’t installed bash via Homebrew, it’s most likely 3.2.57; if you’re on Linux or you’ve manually upgraded, it’s most likely 4.4)
2. Do you have bash-completion installed?

To check both:

```sh
echo $BASH_VERSION
type -t _get_comp_words_by_ref  # will say “function” if bash-completion is available, nothing if not
```

It just occurred to me that I probably used some new 4.x feature in my most recent commits, I’ll see if I can find anything.

One puzzling thing is that you said it just has no effect. I expected some kind of error message. For example, I just tried running this on a brand new Mac, and I got `bash: _get_comp_words_by_ref: command not found` as soon as I pressed Tab.

**Comment by mernen** [comment]
Oh, of course, one possible reason for it not having any effect is that it might not have been loaded.

Can you also run this? It will output “function” if the script was successfully loaded, or nothing if it didn’t load.

```sh
type -t __bundle
```

Did you install/try completion for other commands, like `rake` and `ruby`? How did you install? Via this repo’s instructions or using Homebrew’s `bundler-completion`?

**Comment by mernen** [comment]
I'm closing this issue. Please check the suggestions in the earlier comments, and if you're still having trouble, I've opened the Discussions feature on GitHub.
