### ISSUE TITLE
Use rake -P to give all tasks, rather than just those with descriptions

### ISSUE THREAD

**Issue by grantramsay** [mernen/completion-ruby#8]
Simple change in `completion-rake` seems to work:

        tasks=$("${rake_bin[@]}" --rakefile "$rakefile" --silent --describe 2>/dev/null |
to

        tasks=$("${rake_bin[@]}" --rakefile "$rakefile" --silent -P 2>/dev/null |

**Comment by mernen** [comment]
This was the old behavior, changed in e96f4cbd. The commit message says it used to return some bogus suggestions, but I don’t quite recall how that was triggered.

**Comment by grantramsay** [comment]
Those "bogus suggestions" are probably just the file and directory tasks.
I don't really think a completion tool should be make assumptions on what tasks the user wants displayed.

    # rakefile
    OUTPUT_DIR = 'out'
    OUTPUT_FILE = OUTPUT_DIR + '/output'
    directory OUTPUT_DIR

    file OUTPUT_FILE -> OUTPUT_DIR do
        touch(OUTPUT_FILE)
    end

    task :build -> OUTPUT_FILE
valid tasks:
`rake out`
`rake out/output`
`rake build`
